server:
  port: 6002
spring:
  application:
    name: DemoAPI
  zipkin:
    base-url: http://localhost:6011
  cloud:
    nacos:
      config:
        server-addr: '39.108.120.63:8086'
swagger:
  base-package: com.irskj.cloud
