
spring:
  application:
    name: stream-rmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  cloud:
    stream:
      binders:
        login-topic:
          group: serviceA
          destination: greetings
          consumer:
            partitioned: true
      instance-count: 2
      instance-index: 1
server:
  port: 6009