stages:
 - dev
 - test
 - prod

#生产环境部署
prod:
  stage: prod
  script:
   - pwd
   - echo start build
   - mvn clean package
   - echo ========= build success ==========
   - docker stop demo-api3
   - docker rm demo-api3
   - docker-compose   -f ./docker-compose-dev.yml up -d --build demo-api3
   - echo ========= deploy success ==========
  only:
  - master
