version: '2'

services:
  #custom
  demo-api3:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - my-bridge
    container_name: demo-api3
    image: 39.108.120.63:8090/demo-api3:latest
    ports:
      - "8081:6010"
networks:
  my-bridge:
    driver: bridge
