server:
  port: 7002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
spring:
  application:
    name: Demo-API
  zipkin:
    base-url: http://localhost:6011
swagger:
  base-package: com.irskj.cloud