server:
  port: 6011
spring:
  application:
    name: zipkin-server
management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/